# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('publish', models.BooleanField(default=False, verbose_name='Published')),
                ('date_published', models.DateField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('post_filename', models.CharField(max_length=200, verbose_name='Post Filename')),
            ],
        ),
    ]
