# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django-dropbox-blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('css', 'CSS'), ('js', 'JavaScript'), ('py', 'Python'), ('fd', 'Fundamentals')], default='py', max_length=3),
            preserve_default=False,
        ),
    ]
